@url=http://localhost:8080/api/v1
#@url=http://seelf.docker.localhost/api/v1

GET {{url}}/healthcheck

###

POST {{url}}/sessions
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}

###

DELETE {{url}}/session

###

GET {{url}}/profile

###

PATCH {{url}}/profile
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}

###

PUT {{url}}/profile/key

###

GET {{url}}/targets

###
# @name createTarget

POST {{url}}/targets
Content-Type: application/json

{
    "name": "local docker",
    "url": "http://docker.localhost",
    "docker": {
        
    }
}

###

PATCH {{url}}/targets/{{createTarget.response.body.$.id}}
Content-Type: application/json

{
    "name": "docker outside",
    "url": "http://docker.localhost",
    "docker": {
        
    }
}

###

POST {{url}}/targets/{{createTarget.response.body.$.id}}/reconfigure

###

GET {{url}}/targets/{{createTarget.response.body.$.id}}

###

DELETE {{url}}/targets/{{createTarget.response.body.$.id}}

###

GET {{url}}/registries

###

# @name createRegistry

POST {{url}}/registries
Content-Type: application/json

{
    "name": "Local registry",
    "url": "http://localhost:5000"
}

###

PATCH {{url}}/registries/{{createRegistry.response.body.$.id}}
Content-Type: application/json

{
    "name": "Local registry",
    "url": "http://localhost:5001",
    "credentials": {
        "username": "admin",
        "password": "admin"
    }
}

###

DELETE {{url}}/registries/{{createRegistry.response.body.$.id}}

###

GET {{url}}/registries/{{createRegistry.response.body.$.id}}

###
# @name createApp

POST {{url}}/apps
Content-Type: application/json

{
    "name": "sandbox",
    "version_control": {
        "url": "https://git.voixdu.net/jleicher/go-api-example.git"
    },
    "production": {
        "target": "{{createTarget.response.body.$.id}}",
        "vars": {
            "app": {
                "DEBUG": "false"
            }
        }
    },
    "staging": {
        "target": "{{createTarget.response.body.$.id}}",
        "vars": {
            "app": {
                "DEBUG": "true"
            }
        }
    }
}

###

GET {{url}}/apps

###

GET {{url}}/apps/{{createApp.response.body.$.id}}

###

PATCH {{url}}/apps/{{createApp.response.body.$.id}}
Content-Type: application/json

{
    "version_control": {
        "url": "https://git.voixdu.net/jleicher/go-api-example.git"
    },
    "production": {
        "target": "{{createTarget.response.body.$.id}}"
    },
    "staging": {
        "target": "{{createTarget.response.body.$.id}}"
    }
}

###
# @name queueDeployment

POST {{url}}/apps/{{createApp.response.body.$.id}}/deployments
Content-Type: application/json

{
    "environment": "staging",
    "raw": "services:\n  app:\n    image: traefik/whoami\n    ports:\n      - \"8888:80\"\n\n  two:\n    image: traefik/whoami\n    ports:\n      - \"8889:80\"\n"
}

###

POST {{url}}/apps/{{createApp.response.body.$.id}}/deployments
Content-Type: application/json

{
    "environment": "production",
    "git": {
        "branch": "master",
        "hash": "cf74d09c42"
    }
}

###

POST {{url}}/apps/{{createApp.response.body.$.id}}/deployments
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="environment"

production
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="archive"; filename="go-api.tar.gz"
Content-Type: application/tar+gzip

< ./examples/go-api/go-api.tar.gz
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET {{url}}/apps/{{createApp.response.body.$.id}}/deployments

###

GET {{url}}/apps/{{queueDeployment.response.body.$.app_id}}/deployments/{{queueDeployment.response.body.$.deployment_number}}

###

GET {{url}}/apps/{{queueDeployment.response.body.$.app_id}}/deployments/{{queueDeployment.response.body.$.deployment_number}}/logs

###

DELETE {{url}}/apps/{{createApp.response.body.$.id}}

###

GET {{url}}/jobs