services:
  web:
    restart: unless-stopped
    build: .
    environment:
      - BALANCER_DOMAIN=http://docker.localhost # <- Change this to your own domain, applications will be deployed as subdomains
      - SEELF_ADMIN_EMAIL=admin@example.com # <- Change this
      - SEELF_ADMIN_PASSWORD=admin # <- Change this
      # - DEPLOYMENT_DIR_TEMPLATE={{ .Number }}-{{ .Environment }} # You can configure the deployment build directory path if you want to keep every deployment source files for example.
      # - ACME_EMAIL=youremail@provider.com # <- If BALANCER_DOMAIN starts with https://, let's encrypt certificate will be used and the email associated will default to SEELF_ADMIN_EMAIL but you can override it if you need to
    labels:
      - traefik.enable=true # Here we expose seelf with the traefik instance managed by seelf at startup, that's not mandatory but so much easier
      - traefik.http.routers.seelf.rule=Host(`seelf.docker.localhost`) # <- Change this to where you want seelf to be exposed (use the same domain as above)
      # - traefik.http.routers.seelf.tls.certresolver=seelfresolver # <- If BALANCER_DOMAIN starts with https://, uncomment this line too
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - seelfdata:/seelf/data # The /seelf/data directory contains the database, configuration file and everything deployed by seelf, so keep it :)

volumes:
  seelfdata:

networks:
  default:
    name: seelf-public # Do not change this since this is the network shared by the balancer and deployed applications
