name: CI

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... --cover

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cmd/serve/front
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Check
        run: npm run check

      - name: Test
        run: npm test

  release:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Release
        run: npx -p @semantic-release/git -p @semantic-release/exec semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build and push # Use a custom action to enable caching
        uses: docker/build-push-action@v4
        if: env.docker_publish == 'true'
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ env.docker_tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
